### ISSUE TITLE
SECRET_KEY is null

### ISSUE THREAD

**Issue by cyberorgnizm** [dawilwest/medwebapp#1]
The SECRET_KEY setting must not be empty. it's probably the cause of that error you are getting. Just to be sure, I hope you did set this variable on heroku?

**Comment by cyberorgnizm** [comment]
The app works fine in production. tried running it locally then got that error.

**Comment by dawilwest** [comment]
The Secret Key is set in such a way that it will only be True if one creates an environment variable for the it on your own personal system, if not it would run it as false.
